// PLACEHOLDER LORE — replace with real in-character writing.

const CODEX_DATA = {
  'elden-ring': {
    categories: [
      { id: 'bosses',     label: 'Bosses',     icon: '⚔' },
      { id: 'items',      label: 'Items',      icon: '🜲' },
      { id: 'locations',  label: 'Locations',  icon: '🏰' },
      { id: 'characters', label: 'Characters', icon: '👤' },
    ],
    entries: [
      {
        id: 'er-001',
        category: 'bosses',
        name: 'Margit, the Fell Omen',
        type: 'BOSS · OMEN',
        sigil: '⚔',
        snippet: 'Clad in chains that were never shackles, only ornament.',
        body: [
          'Margit bars the road to Stormveil with the patience of something that has waited centuries and found the waiting unremarkable. He is not a guardian — he is a verdict, handed down by grace itself to every Tarnished who presumes too much, too soon.',
          'His tail is a weapon. His staff is a conjured thing, made of golden light he clearly despises. He fights the way a disappointed elder fights: with thorough, joyless efficiency.',
        ],
        quote: '"Thou art not yet Elden Lord. I will not suffer a fool upon that throne."',
        stats: { Location: 'Stormhill, Limgrave', Weakness: 'Holy Damage', Reward: 'Talisman Pouch' },
      },
      {
        id: 'er-002',
        category: 'bosses',
        name: 'Rennala, Queen of the Full Moon',
        type: 'BOSS · DEMIGOD',
        sigil: '🌕',
        snippet: 'She cradles amber eggs and hums to things that will not hatch.',
        body: [
          'Once Rennala was the Grand Academy\'s beating heart — a scholar who pulled moonlight down from the sky and taught it to burn. Now she sits in the Grand Library, rocking in a reverie that even the Carian knights who still love her cannot reach.',
          'Her children shattered her amber egg when Radagon left. The Full Moon she summons still shines, but it shines on ruins she no longer notices.',
        ],
        quote: '"O, come now. Shall we give you a new life?"',
        stats: { Location: 'Raya Lucaria Academy', Weakness: 'Fire Damage', Reward: 'Great Rune of the Unborn' },
      },
      {
        id: 'er-003',
        category: 'items',
        name: 'Erdleaf Flower',
        type: 'ITEM · REAGENT',
        sigil: '🜲',
        snippet: 'Petal like hammered gold. Roots that drink from something deeper than soil.',
        body: [
          'The Erdleaf flower grows only where the Erdtree\'s roots have brushed the earth and moved on. Alchemists prize the dried petals for their slow combustion. Herbalists prize them for nothing, because herbalists lack imagination.',
          'When ground to a fine paste it tastes of copper and faint regret — the reliable taste of grace-touched things.',
        ],
        quote: '"Where the roots have rested, something golden always follows."',
        stats: { Location: 'Limgrave, Liurnia', Weakness: 'N/A', Reward: 'Crafting — Fire Grease' },
      },
      {
        id: 'er-004',
        category: 'items',
        name: 'Larval Tear',
        type: 'ITEM · REBIRTH',
        sigil: '🥚',
        snippet: 'A wriggling mercy pressed into stone form.',
        body: [
          'The Silver Tears are not native to the Lands Between — they fell from the moon. A larval tear is what forms when a Silver Tear dies before it finds a shape worth keeping. Inside each one, Rennala claims she can hear a heartbeat.',
          'Tarnished who bring them to the Queen receive a new body in exchange. Whether this constitutes kindness or transactional forgetting is a theological question no one has had the courage to press.',
        ],
        quote: '"Born anew. Unburdened. For a time."',
        stats: { Location: 'Nokron, Limgrave', Weakness: 'N/A', Reward: 'Rebirth (via Rennala)' },
      },
      {
        id: 'er-005',
        category: 'locations',
        name: 'Stormveil Castle',
        type: 'LOCATION · STRONGHOLD',
        sigil: '🏰',
        snippet: 'The gate has not opened willingly in an age.',
        body: [
          'Stormveil was built to be a problem — narrow bridges, murder-holes cut into walls that used to be diplomatic corridors, soldiers who fight with the quiet determination of men who have been waiting for permission to stop. Godrick inherited it and never stopped adding to its maze.',
          'The birds in the courtyard are too large. No one mentions this.',
        ],
        quote: '"Every stone here was laid to delay you."',
        stats: { Location: 'Limgrave — Northwest', Weakness: 'Artillery Gaps', Reward: 'Godrick\'s Great Rune' },
      },
      {
        id: 'er-006',
        category: 'locations',
        name: 'Lake of Rot',
        type: 'LOCATION · BLIGHTED',
        sigil: '🜸',
        snippet: 'The stars reflected here are not the real stars.',
        body: [
          'The Lake of Rot is less a lake and more a theological argument rendered in scarlet water. It was not always rot — once it was part of the underground road to Nokstella. Astel changed that, or something that came before Astel did.',
          'Travelers who survive the crossing report that the reflection of the ceiling shows stars in configurations that do not exist above ground. Researchers who went back to confirm this did not return.',
        ],
        quote: '"The rot does not hate you. It is simply indifferent."',
        stats: { Location: 'Ainsel River — Deep', Weakness: 'Preserving Boluses', Reward: 'Passage to Astel' },
      },
      {
        id: 'er-007',
        category: 'characters',
        name: 'Melina',
        type: 'CHARACTER · MAIDEN',
        sigil: '🕯',
        snippet: 'One eye sealed shut. She says there is nothing worth seeing in it.',
        body: [
          'Melina appears at the first Site of Grace you touch and explains, with a professionalism that borders on eerie, that she will help you reach the Erdtree in exchange for something she will not yet name. This is the second-oldest offer in the Lands Between.',
          'She burns at the end if you let her. She is entirely fine with this. This is the most disturbing fact about her.',
        ],
        quote: '"I am kindling. Use me well."',
        stats: { Location: 'Wherever you are', Weakness: 'Frenzied Flame (her concern, not yours)', Reward: 'Torrent, Spectral Steed Whistle' },
      },
      {
        id: 'er-008',
        category: 'characters',
        name: 'Fia, Deathbed Companion',
        type: 'CHARACTER · DEATHBED',
        sigil: '🌑',
        snippet: 'She holds you like something she is trying to preserve.',
        body: [
          'Fia sits in the Roundtable Hold and offers the Tarnished her embrace, which provides a small buff and a much larger philosophical implication. She is not deceptive. She believes in what she is doing. This is somehow more unsettling than deception.',
          'She serves the Gloam-Eyed Queen — or the memory of her — and wants a death for the Lands Between that is gentler than the one the Erdtree offers. Whether she is right is above the pay grade of anyone who speaks to her in the Hold.',
        ],
        quote: '"Hold me, just for a while. The living need warmth too."',
        stats: { Location: 'Roundtable Hold', Weakness: 'Blunt honesty', Reward: 'Baldachin\'s Blessing, Mending Rune of the Death-Prince' },
      },
    ],
  },

  'ghibli': {
    categories: [
      { id: 'spirits',    label: 'Spirits',    icon: '✨' },
      { id: 'flora',      label: 'Flora',      icon: '🌿' },
      { id: 'places',     label: 'Places',     icon: '🏡' },
      { id: 'companions', label: 'Companions', icon: '🐾' },
    ],
    entries: [
      {
        id: 'gh-001',
        category: 'spirits',
        name: 'The Camphor Keeper',
        type: 'SPIRIT · ANCIENT',
        sigil: '🌳',
        snippet: 'Older than the valley. Patient the way only trees are patient.',
        body: [
          'The Camphor Keeper lives in the oldest tree in the forest, which is also, by some measures, the forest itself. Children who get lost near its roots are always found by morning, no worse for it, occasionally holding flowers that do not grow in this region.',
          'It does not speak in words. It speaks in the way the light changes when you have been anxious for too long — softening until you notice it and breathe.',
        ],
        quote: '"The forest does not lose things. It holds them until they are ready to be found."',
        stats: { Habitat: 'Ancient Camphor Grove', Temperament: 'Deeply Gentle', Gift: 'Direction to the lost' },
      },
      {
        id: 'gh-002',
        category: 'spirits',
        name: 'Kodama (White Wood-Sprite)',
        type: 'SPIRIT · MINOR',
        sigil: '🤍',
        snippet: 'A flicker at the corner of vision. Gone before you look.',
        body: [
          'Kodama are the sign that a forest is healthy. When they vanish from a grove, the trees begin to go quiet — not dying, exactly, but becoming merely wood. Foresters who have worked old-growth land their whole lives can tell the difference in the sound of the wind.',
          'They are not shy so much as uninterested in being observed. A kodama noticed is a kodama already elsewhere.',
        ],
        quote: '"To see one clearly is to have misunderstood what you were looking at."',
        stats: { Habitat: 'Old-growth forest', Temperament: 'Elusive', Gift: 'Forest health indicator' },
      },
      {
        id: 'gh-003',
        category: 'flora',
        name: 'Moongrass',
        type: 'FLORA · LUMINESCENT',
        sigil: '🌙',
        snippet: 'Grows only where moonlight has pooled overnight and not yet drained away.',
        body: [
          'Moongrass holds light the way still water holds the sky — not producing it, just refusing to let it go. It is most visible on overcast nights, which is the only useful thing that can be said about its ecology.',
          'The sisters who tend the mountain shrine weave dried moongrass into the paper lanterns for the late-summer festival. They say it keeps the lanterns lit through rain.',
        ],
        quote: '"Some things are brightened not by what they contain but by what they refuse to forget."',
        stats: { Habitat: 'Moonlit clearings, still ponds', Temperament: 'N/A — flora', Gift: 'Lanternweaving, gentle light' },
      },
      {
        id: 'gh-004',
        category: 'flora',
        name: 'Spirit-Moss',
        type: 'FLORA · INDICATOR',
        sigil: '🍀',
        snippet: 'It grows where the boundary is thin. Older folk will not pick it.',
        body: [
          'Spirit-moss grows on the stones that mark the edge of the deep forest, the ones that nobody placed but everyone respects. Herbalists argue about whether it has any medicinal value. The argument is always settled by the oldest person in the room going quiet.',
          'Children use it as a game — whoever finds the most patches in an afternoon gets their choice of supper. This is considered good luck training.',
        ],
        quote: '"Where the moss is thickest, step carefully. Not from danger. From respect."',
        stats: { Habitat: 'Forest boundary stones, old paths', Temperament: 'N/A — flora', Gift: 'Marks spirit pathways' },
      },
      {
        id: 'gh-005',
        category: 'places',
        name: 'The Valley of Wind',
        type: 'PLACE · SACRED',
        sigil: '🌬',
        snippet: 'The insects there fly in spirals. Always the same direction.',
        body: [
          'The Valley of Wind is a geographic fact and a spiritual condition. Travelers who pass through it often describe a sense that they have been thinking about something important for years and only just remembered what it was. No one has been able to name the feeling precisely.',
          'A young princess once stood at its edge for three days, watching the wind patterns. She came back and drew maps the older engineers still consult.',
        ],
        quote: '"The wind does not go where it is aimed. It goes where it is needed."',
        stats: { Habitat: 'High plateau, southwestern range', Temperament: 'Capricious, ultimately benevolent', Gift: 'Wind-reading, clarity of purpose' },
      },
      {
        id: 'gh-006',
        category: 'places',
        name: 'Bathhouse of the Between',
        type: 'PLACE · LIMINAL',
        sigil: '🏮',
        snippet: 'Always busy. No one can say exactly how they got the reservation.',
        body: [
          'The Bathhouse sits at a crossroads that is not on any map — or rather, it is on every map from a slightly different period, never quite in the same position, which amounts to the same thing. Its guests include beings from both sides of the boundary, and the staff are professionally incurious.',
          'The food is excellent. The tea is better. The prices are in a currency that appears in your pocket without explanation.',
        ],
        quote: '"Work hard. Remember your name. Everything else is negotiable."',
        stats: { Habitat: 'Liminal crossing-point, fluid location', Temperament: 'Busy, orderly', Gift: 'Restoration, identity (if retained)' },
      },
      {
        id: 'gh-007',
        category: 'companions',
        name: 'Totoro (Great Forest Spirit)',
        type: 'COMPANION · GUARDIAN',
        sigil: '🐾',
        snippet: 'He sleeps through most emergencies. This is a form of confidence.',
        body: [
          'Totoro is not a god and is not quite an animal. He is the forest in a mood to be friendly — large and grey and smelling of old rain, liable to appear at bus stops during thunderstorms if the person waiting is young enough or frightened enough or both.',
          'He is not always visible to adults. This is not about belief. It is about what adults have agreed to look at.',
        ],
        quote: '"He offered me his umbrella. I don\'t think he needed it."',
        stats: { Habitat: 'Ancient camphor groves, hollow trees', Temperament: 'Sleepy, profoundly benign', Gift: 'Comfort, passage, acorn-sowing' },
      },
      {
        id: 'gh-008',
        category: 'companions',
        name: 'House Spirits (Makkuro Kurosuke)',
        type: 'COMPANION · MINOR SPIRIT',
        sigil: '🖤',
        snippet: 'They scatter when light comes in. They were only keeping the dark company.',
        body: [
          'Soot sprites occupy old buildings the way old buildings deserve to be occupied — attentively, cheaply, without complaint. They eat dust and silence and produce nothing visible in return, which is a better deal than most tenants offer.',
          'Children see them in empty rooms. The sprites, for their part, see children as a reasonable threat and treat them accordingly: by disappearing.',
        ],
        quote: '"An old house is never empty. It is just full of different things."',
        stats: { Habitat: 'Abandoned rooms, unlit staircases', Temperament: 'Skittish, peaceable', Gift: 'Keeping the dark inhabited' },
      },
    ],
  },

  got: {
    categories: [
      { id: 'lords',     label: 'Lords',     icon: '👑' },
      { id: 'creatures', label: 'Creatures', icon: '🐉' },
      { id: 'seats',     label: 'Seats',     icon: '🏰' },
      { id: 'artifacts', label: 'Artifacts', icon: '⚔' },
    ],
    entries: [
      {
        id: 'gt-001',
        category: 'lords',
        name: 'The Three-Eyed Raven',
        type: 'LORD · SEER',
        sigil: '🐦‍⬛',
        snippet: 'He waited a thousand years for you specifically. Try not to be flattered.',
        body: [
          'The Three-Eyed Raven sat in the roots of a weirwood tree long enough that the tree began to grow through him, which he apparently found acceptable. He sees everything that has happened — a less useful skill than advertised, since history\'s primary function appears to be repeating itself regardless of audience.',
          'His method of instruction is withholding information until the relevant crisis is already underway. There is a philosophy behind this. Whether it is a good philosophy is a separate question from whether it works.',
        ],
        quote: '"You will never walk again. But you will fly."',
        stats: { Location: 'Beyond the Wall, weirwood cave', Weakness: 'Icy cavalry', Reward: 'Greensight, the weight of all memory' },
      },
      {
        id: 'gt-002',
        category: 'lords',
        name: 'Cersei Lannister',
        type: 'LORD · QUEEN REGENT',
        sigil: '🦁',
        snippet: 'She loves her children and her wine and not much else, and she is honest about it.',
        body: [
          'Cersei Lannister is the most politically competent person in King\'s Landing on her best day, which is a low bar given the company, but she clears it with energy. She plays the game with genuine skill and the constant disadvantage of everyone around her needing her to play it more quietly.',
          'Her primary strategic error is confusing "outlasting" with "winning." To be fair, this is most people\'s error. She makes it more consequentially than most.',
        ],
        quote: '"When you play the game of thrones, you win or you die."',
        stats: { Location: 'King\'s Landing, Red Keep', Weakness: 'Prophecy (self-fulfilling variety)', Reward: 'Political intelligence, wildfire expertise' },
      },
      {
        id: 'gt-003',
        category: 'creatures',
        name: 'Drogon',
        type: 'CREATURE · DRAGON',
        sigil: '🐉',
        snippet: 'The largest. The most attached. The one that stayed.',
        body: [
          'Drogon is named for a dead man and bonded to a living woman and is, by most measurements, the most dangerous single entity west of the Jade Sea. He burned the Loot Train. He burned Valyria. He burned a fair amount of King\'s Landing on an afternoon that historians will spend centuries contextualizing.',
          'He ultimately carried his rider\'s body somewhere that was not mapped, which is the most dragon thing a dragon has ever done.',
        ],
        quote: '"He is not a weapon. He is a consequence."',
        stats: { Location: 'Variable — last seen eastern continent', Weakness: 'Scorpion bolt, poor leadership decisions', Reward: 'Decisive air superiority' },
      },
      {
        id: 'gt-004',
        category: 'creatures',
        name: 'The Night King',
        type: 'CREATURE · WHITE WALKER',
        sigil: '❄',
        snippet: 'He has no dialogue. He doesn\'t need any. The temperature drop says everything.',
        body: [
          'The Night King was a First Man pressed onto a dragonglass blade by the Children of the Forest, which is the kind of defensive measure that benefits from a clear exit strategy. He spent several thousand years accumulating an army of the dead and expressing himself exclusively through ominous eye contact.',
          'His tactical patience was extraordinary. His weakness was a young woman with a Valyrian steel knife and a sound approach to misdirection.',
        ],
        quote: '"[silence]"',
        stats: { Location: 'North of the Wall, then increasingly south of it', Weakness: 'Dragonglass, Valyrian steel, Arya Stark', Reward: 'Nothing recoverable; he leaves very little behind' },
      },
      {
        id: 'gt-005',
        category: 'seats',
        name: 'Winterfell',
        type: 'SEAT · STRONGHOLD',
        sigil: '🏰',
        snippet: 'It has been burned twice. It is still there. Draw your own conclusions.',
        body: [
          'Winterfell is less a castle and more an argument the North makes about permanence. It was built to be difficult — not pretty-difficult like Highgarden, but stone-and-glacial-spring difficult, the kind that says we did not build this to impress you. We built this to outlast you.',
          'The crypts below it are older than anything above ground. The Starks keep their dead there and visit them on occasions that require perspective.',
        ],
        quote: '"The North remembers. Winterfell is why."',
        stats: { Location: 'The North, south of the Last Hearth', Weakness: 'Betrayal from within (historically recurring)', Reward: 'Defensible position, psychological home ground' },
      },
      {
        id: 'gt-006',
        category: 'seats',
        name: 'Dragonstone',
        type: 'SEAT · VOLCANIC FORTRESS',
        sigil: '🌋',
        snippet: 'Carved by dragonfire. Still smells faintly of it.',
        body: [
          'Dragonstone was the Targaryen seat before there was a Westeros to rule, and its architecture reflects this — everything carved by dragonflame into shapes that make structural engineers uneasy. The Painted Table shows Westeros as the Targaryens first saw it: a thing to be crossed.',
          'It sits atop significant deposits of dragonglass, which took everyone approximately several thousand years to notice. Mining started when it became urgent.',
        ],
        quote: '"This is where it began. Whether it ends here is a different question."',
        stats: { Location: 'Blackwater Bay, east of King\'s Landing', Weakness: 'Supply chains, isolation', Reward: 'Dragonglass deposits, symbolic weight' },
      },
      {
        id: 'gt-007',
        category: 'artifacts',
        name: 'Longclaw',
        type: 'ARTIFACT · VALYRIAN STEEL',
        sigil: '⚔',
        snippet: 'A bastard\'s sword. A lord\'s sword. In the end, both.',
        body: [
          'Longclaw was a Mormont sword — bear\'s head pommel, centuries of Northern winters in the steel — until Jeor Mormont gave it to a boy who had saved his life in the dark beyond the Wall. The pommel was recast to a wolf. The boy became a man who kept being given things he didn\'t ask for.',
          'Valyrian steel holds an edge that regular steel cannot match and kills White Walkers that regular steel cannot touch. These properties have not stopped it from living very close to very many near-death experiences.',
        ],
        quote: '"It has been in my family for five centuries. It was always going to end up with a Stark."',
        stats: { Location: 'Castle Black, then wherever Jon Snow is', Weakness: 'N/A — the sword is fine; the wielder is complicated', Reward: 'White Walker destruction, status, moral burden' },
      },
      {
        id: 'gt-008',
        category: 'artifacts',
        name: 'The Iron Throne',
        type: 'ARTIFACT · SEAT OF POWER',
        sigil: '👑',
        snippet: 'One thousand swords. Zero comfortable sitting positions. This was intentional.',
        body: [
          'Aegon the Conqueror had the swords of his enemies melted down and forged into a throne, which is a statement about power that the subsequent three hundred years of dynastic collapse have not exactly refuted. The throne cuts those who sit on it, which maesters call symbolic and surgeons call predictable.',
          'It was destroyed in a dragon\'s final act of editorial judgment. What replaced it is smaller, more comfortable, and — the Seven Kingdoms will discover — no less difficult to keep.',
        ],
        quote: '"A king should never sit easy. The blades are a reminder."',
        stats: { Location: 'Formerly the Red Keep, King\'s Landing; currently: rubble', Weakness: 'Dragon fire (ultimately)', Reward: 'Theoretical sovereignty over all Seven Kingdoms' },
      },
    ],
  },
};

export default CODEX_DATA;
